### ISSUE TITLE
Base article

### ISSUE THREAD

**Issue by taadaal** [vsskarthik/noxim-new#1]
Hello, 
could I read the article used in this project?

**Comment by vsskarthik** [comment]
Hi,
This is a forked project, which contains the modification specific to our personal project. You can find the original repository here
[https://github.com/davidepatti/noxim](url).

**Comment by taadaal** [comment]
Thanks for the quick response, I have the original Noxim and want to understand your source code CAOE and CAXY.
Is there any article close to your project that I can read?

**Comment by vsskarthik** [comment]
Got it,
Yes you can read original CAOE paper which states the algorithm clearly
[https://iopscience.iop.org/article/10.1088/1674-4926/39/12/125006/meta](url)

The CAOE and CAXY is implemented in the same way

**Comment by taadaal** [comment]
I really appreciate 🙏 but I couldn't open the link would you email the article to me? 
tandi93@yahoo.com

**Comment by taadaal** [comment]
I appreciate 🙏 thanks for responding, have a good day.
